django_site/mysite/app_menu/urls.py
from django.urls import path

from app_menu.views import HomeView

app_name = 'app_menu'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
]

django_site/mysite/app_pages/urls.py
from django.urls import path

from app_pages.views import (
    Page1View,
    Page11View,
    Page12View,
    Page121View,
    Page122View,
    Page13View,
    Page14View,
    Page2View,
    Page21View,
    Page211View,
    Page212View,
    Page2121View,
    Page2122View,
    Page22View,
    Page3View,
    Page31View,
    Page4View,
    Page41View,
    Page411View,
    Page412View,
    Page413View,
)

app_name = 'app_pages'

urlpatterns = [
    path('1/', Page1View.as_view(), name='page_1'),
    path('1/1/', Page11View.as_view(), name='page_1_1'),
    path('1/2/', Page12View.as_view(), name='page_1_2'),
    path('1/2/1/', Page121View.as_view(), name='page_1_2_1'),
    path('1/2/2/', Page122View.as_view(), name='page_1_2_2'),
    path('1/3/', Page13View.as_view(), name='page_1_3'),
    path('1/4/', Page14View.as_view(), name='page_1_4'),
    path('2/', Page2View.as_view(), name='page_2'),
    path('2/1/', Page21View.as_view(), name='page_2_1'),
    path('2/1/1/', Page211View.as_view(), name='page_2_1_1'),
    path('2/1/2/', Page212View.as_view(), name='page_2_1_2'),
    path('2/1/2/1/', Page2121View.as_view(), name='page_2_1_2_1'),
    path('2/1/2/2/', Page2122View.as_view(), name='page_2_1_2_2'),
    path('2/2/', Page22View.as_view(), name='page_2_2'),
    path('3/', Page3View.as_view(), name='page_3'),
    path('3/1/', Page31View.as_view(), name='page_3_1'),
    path('4/', Page4View.as_view(), name='page_4'),
    path('4/1/', Page41View.as_view(), name='page_4_1'),
    path('4/1/1/', Page411View.as_view(), name='page_4_1_1'),
    path('4/1/2/', Page412View.as_view(), name='page_4_1_2'),
    path('4/1/3/', Page413View.as_view(), name='page_4_1_3'),
]

django_site/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('app_menu.urls')),
    path('page/', include('app_pages.urls')),
]

django_site/mysite/app_menu/models.py
from django.db import models


class Menu(models.Model):
    name = models.CharField(max_length=100, verbose_name='Menu name')

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = 'Menu'
        verbose_name_plural = 'Menus'


class MenuItem(models.Model):
    title = models.CharField(max_length=100, verbose_name='Title')
    url_name = models.CharField(max_length=100, verbose_name='Named URl')

    menu = models.ForeignKey(Menu, blank=True, related_name='items', on_delete=models.CASCADE)
    parent = models.ForeignKey('self', blank=True, null=True, related_name='childs', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Menu item'
        verbose_name_plural = 'Menu items'

    def __str__(self):
        return str(self.title)

django_site/mysite/app_pages/models.py
from django.db import models # noqa

# Create your models here.

django_site/mysite/app_menu/views.py
from django.http import HttpRequest, HttpResponse
from django.views import View
from django.shortcuts import render


class HomeView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        template_name = 'app_menu/home.html'
        return render(request, template_name)

django_site/mysite/app_pages/views.py
from django.views.generic import TemplateView

from app_pages.apps import AppPagesConfig

app_name = AppPagesConfig.name


class Page1View(TemplateView):
    name = '1.html'
    view_name = 'page_1'
    template_name = f'{app_name}/{name}'
    extra_context = {'url_name': f'{app_name}:{view_name}'}


class Page11View(TemplateView):
    name = '1.1.html'
    view_name = 'page_1_1'
    template_name = f'{app_name}/{name}'
    extra_context = {'url_name': f'{app_name}:{view_name}'}


class Page12View(TemplateView):
    name = '1.2.html'
    view_name = 'page_1_2'
    template_name = f'{app_name}/{name}'
    extra_context = {'url_name': f'{app_name}:{view_name}'}


class Page121View(TemplateView):
    name = '1.2.1.html'
    view_name = 'page_1_2_1'
    template_name = f'{app_name}/{name}'
    extra_context = {'url_name': f'{app_name}:{view_name}'}


class Page122View(TemplateView):
    name = '1.2.2.html'
    view_name = 'page_1_2_2'
    template_name = f'{app_name}/{name}'
    extra_context = {'url_name': f'{app_name}:{view_name}'}


class Page13View(TemplateView):
    name = '1.3.html'
    view_name = 'page_1_3'
    template_name = f'{app_name}/{name}'
    extra_context = {'url_name': f'{app_name}:{view_name}'}


class Page14View(TemplateView):
    name = '1.4.html'
    view_name = 'page_1_4'
    template_name = f'{app_name}/{name}'
    extra_context = {'url_name': f'{app_name}:{view_name}'}


class Page2View(TemplateView):
    name = '2.html'
    view_name = 'page_2'
    template_name = f'{app_name}/{name}'
    extra_context = {'url_name': f'{app_name}:{view_name}'}


class Page21View(TemplateView):
    name = '2.1.html'
    view_name = 'page_2_1'
    template_name = f'{app_name}/{name}'
    extra_context = {'url_name': f'{app_name}:{view_name}'}


class Page211View(TemplateView):
    name = '2.1.1.html'
    view_name = 'page_2_1_1'
    template_name = f'{app_name}/{name}'
    extra_context = {'url_name': f'{app_name}:{view_name}'}


class Page212View(TemplateView):
    name = '2.1.2.html'
    view_name = 'page_2_1_2'
    template_name = f'{app_name}/{name}'
    extra_context = {'url_name': f'{app_name}:{view_name}'}


class Page2121View(TemplateView):
    name = '2.1.2.1.html'
    view_name = 'page_2_1_2_1'
    template_name = f'{app_name}/{name}'
    extra_context = {'url_name': f'{app_name}:{view_name}'}


class Page2122View(TemplateView):
    name = '2.1.2.2.html'
    view_name = 'page_2_1_2_2'
    template_name = f'{app_name}/{name}'
    extra_context = {'url_name': f'{app_name}:{view_name}'}


class Page22View(TemplateView):
    name = '2.2.html'
    view_name = 'page_2_2'
    template_name = f'{app_name}/{name}'
    extra_context = {'url_name': f'{app_name}:{view_name}'}


class Page3View(TemplateView):
    name = '3.html'
    view_name = 'page_3'
    template_name = f'{app_name}/{name}'
    extra_context = {'url_name': f'{app_name}:{view_name}'}


class Page31View(TemplateView):
    name = '3.1.html'
    view_name = 'page_3_1'
    template_name = f'{app_name}/{name}'
    extra_context = {'url_name': f'{app_name}:{view_name}'}


class Page4View(TemplateView):
    name = '4.html'
    view_name = 'page_4'
    template_name = f'{app_name}/{name}'
    extra_context = {'url_name': f'{app_name}:{view_name}'}


class Page41View(TemplateView):
    name = '4.1.html'
    view_name = 'page_4_1'
    template_name = f'{app_name}/{name}'
    extra_context = {'url_name': f'{app_name}:{view_name}'}


class Page411View(TemplateView):
    name = '4.1.1.html'
    view_name = 'page_4_1_1'
    template_name = f'{app_name}/{name}'
    extra_context = {'url_name': f'{app_name}:{view_name}'}


class Page412View(TemplateView):
    name = '4.1.2.html'
    view_name = 'page_4_1_2'
    template_name = f'{app_name}/{name}'
    extra_context = {'url_name': f'{app_name}:{view_name}'}


class Page413View(TemplateView):
    name = '4.1.3.html'
    view_name = 'page_4_1_3'
    template_name = f'{app_name}/{name}'
    extra_context = {'url_name': f'{app_name}:{view_name}'}

django_site/mysite/app_menu/templates/app_menu/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>
    {% block title %}
    Base title
    {% endblock %}
  </title>
</head>
<body>
{% block body %}
Base body
{% endblock %}
</body>
</html>

django_site/mysite/app_menu/templates/app_menu/home.html
{% extends 'app_menu/base.html' %}

{% block title %}
Main menu
{% endblock %}

{% block body %}

{% load common_tags %}
{% draw_menu 'Main menu' 0 %}

{% endblock %}

django_site/mysite/app_menu/templates/app_menu/main_menu.html
<ul class="main-menu">
  {% for item in items %}
  <li>
    <a href="{% url item.item.url_name %}">{{ item.item.title }}</a>
    {% if item.childs %}
    {% include 'app_menu/main_menu.html' with items=item.childs %}
    {% endif %}
  </li>
  {% endfor %}
</ul>

django_site/mysite/app_pages/templates/app_pages/1.1.html
{% extends 'app_pages/base.html' %}

{% block title %}
Page #1.1
{% endblock %}

{% block body %}
<h2>
  Body 1.1
</h2>

{% load common_tags %}
{% draw_menu 'Main menu' url_name %}

<a href="{% url 'app_menu:home' %}">Home</a>
{% endblock %}

django_site/mysite/app_pages/templates/app_pages/1.2.1.html
{% extends 'app_pages/base.html' %}

{% block title %}
Page #1.2.1
{% endblock %}

{% block body %}
<h2>
  Body 1.2.1
</h2>

{% load common_tags %}
{% draw_menu 'Main menu' url_name %}

<a href="{% url 'app_menu:home' %}">Home</a>
{% endblock %}

django_site/mysite/app_pages/templates/app_pages/1.2.2.html
{% extends 'app_pages/base.html' %}

{% block title %}
Page #1.2.2
{% endblock %}

{% block body %}
<h2>
  Body 1.2.2
</h2>

{% load common_tags %}
{% draw_menu 'Main menu' url_name %}

<a href="{% url 'app_menu:home' %}">Home</a>
{% endblock %}

django_site/mysite/app_pages/templates/app_pages/1.3.html
{% extends 'app_pages/base.html' %}

{% block title %}
Page #1.3
{% endblock %}

{% block body %}
<h2>
  Body 1.3
</h2>

{% load common_tags %}
{% draw_menu 'Main menu' url_name %}

<a href="{% url 'app_menu:home' %}">Home</a>
{% endblock %}

django_site/mysite/app_pages/templates/app_pages/1.html
{% extends 'app_pages/base.html' %}

{% block title %}
Page #1
{% endblock %}

{% block body %}
<h2>
  Body 1
</h2>

{% load common_tags %}
{% draw_menu 'Main menu' url_name %}

<a href="{% url 'app_menu:home' %}">Home</a>
{% endblock %}

django_site/mysite/app_pages/templates/app_pages/2.1.2.2.html
{% extends 'app_pages/base.html' %}

{% block title %}
Page #2.1.2.2
{% endblock %}

{% block body %}
<h2>
  Body 2.1.2.2
</h2>

{% load common_tags %}
{% draw_menu 'Main menu' url_name %}
<br>
{% draw_menu 'New menu' url_name %}
<a href="{% url 'app_menu:home' %}">Home</a>
{% endblock %}

django_site/mysite/app_pages/templates/app_pages/2.1.html
{% extends 'app_pages/base.html' %}

{% block title %}
Page #2.1
{% endblock %}

{% block body %}
<h2>
  Body 2.1
</h2>

{% load common_tags %}
{% draw_menu 'Main menu' url_name %}
<br>
{% draw_menu 'New menu' url_name %}
<a href="{% url 'app_menu:home' %}">Home</a>
{% endblock %}

django_site/mysite/app_pages/templates/app_pages/2.2.html
{% extends 'app_pages/base.html' %}

{% block title %}
Page #2.2
{% endblock %}

{% block body %}
<h2>
  Body 2.2
</h2>

{% load common_tags %}
{% draw_menu 'Main menu' url_name %}
<br>
{% draw_menu 'New menu' url_name %}
<a href="{% url 'app_menu:home' %}">Home</a>
{% endblock %}

django_site/mysite/app_pages/templates/app_pages/2.html
{% extends 'app_pages/base.html' %}

{% block title %}
Page #2
{% endblock %}

{% block body %}
<h2>
  Body 2
</h2>

{% load common_tags %}
{% draw_menu 'Main menu' url_name %}
<br>
{% draw_menu 'New menu' url_name %}

<a href="{% url 'app_menu:home' %}">Home</a>
{% endblock %}

django_site/mysite/app_pages/templates/app_pages/3.html
{% extends 'app_pages/base.html' %}

{% block title %}
Page #3
{% endblock %}

{% block body %}
<h2>
  Body 3
</h2>

{% load common_tags %}
{% draw_menu 'Main menu' url_name %}

<a href="{% url 'app_menu:home' %}">Home</a>
{% endblock %}

django_site/mysite/app_pages/templates/app_pages/4.1.1.html
{% extends 'app_pages/base.html' %}

{% block title %}
Page #4.1.1
{% endblock %}

{% block body %}
<h2>
  Body 4.1.1
</h2>

{% load common_tags %}
{% draw_menu 'Main menu' url_name %}

<a href="{% url 'app_menu:home' %}">Home</a>
{% endblock %}

django_site/mysite/app_pages/templates/app_pages/4.1.2.html
{% extends 'app_pages/base.html' %}

{% block title %}
Page #4.1.2
{% endblock %}

{% block body %}
<h2>
  Body 4.1.2
</h2>

{% load common_tags %}
{% draw_menu 'Main menu' url_name %}

<a href="{% url 'app_menu:home' %}">Home</a>
{% endblock %}

django_site/mysite/app_pages/templates/app_pages/4.1.html
{% extends 'app_pages/base.html' %}

{% block title %}
Page #4.1
{% endblock %}

{% block body %}
<h2>
  Body 4.1
</h2>

{% load common_tags %}
{% draw_menu 'Main menu' url_name %}

<a href="{% url 'app_menu:home' %}">Home</a>
{% endblock %}

django_site/mysite/app_pages/templates/app_pages/4.html
{% extends 'app_pages/base.html' %}

{% block title %}
Page #4
{% endblock %}

{% block body %}
<h2>
  Body 4
</h2>

{% load common_tags %}
{% draw_menu 'Main menu' url_name %}

<a href="{% url 'app_menu:home' %}">Home</a>
{% endblock %}